data_1<-read.table(file="household_power_consumption.txt",header = TRUE,sep=";",stringsAsFactors = FALSE)
data_2<-rbind(subset(data_1, Date == "1/2/2007"),subset(data_1, Date == "2/2/2007"))
png(filename="plot2.png", width = 480, height = 480, units = "px")
data_2$Date <- as.Date(data_2$Date, "%d/%m/%Y")
time <- paste(data_2$Date, data_2$Time)
time <- strptime(time, "%Y-%m-%d %H:%M:%S")
plot(time,as.numeric(data_2$Global_active_power), type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png, file="plot2.png")
dev.off()
